### ISSUE TITLE
Update the stylesheet to address Extent display issues for FAs from ArchivesSpace

### ISSUE THREAD

**Issue by mtkidd** [VAheritage/xtf#5]
Submitted by: Courtney Tkacz

Sample: https://ead.lib.virginia.edu/vivaxtf/view?docId=oai/vmfa/repositories/2/resources/44.oai_ead.xml

The number, type, container summary, and physical details part of the note are running together without punctuation (e.g. "160.25 Linear Feet 129 boxes; 4,220 folders VMFA Holdings"). I'm not sure you need anything besides the number and type?

**Comment by sdm7g** [comment]
https://github.com/VAheritage/xtf/commit/f2f54a16e5ada8c3901f907cfd29c81650f8c53d 

In template match= archdesc/did/repository       | archdesc/did/origination       | archdesc/did/physdesc       | archdesc/did/unitid       | archdesc/did/physloc       | archdesc/did/abstract       | archdesc/did/langmaterial       | archdesc/did/materialspec  
specialcase physdesc. Instead of apply-templates,  join text strings with comma separator. 

Now displays as:
   **Quantity**  160.25 Linear Feet, 129 boxes; 4,220 folders, VMFA Holdings
   **Quantity**  81.85 cu. ft., 91 boxes; 3,276 folders, Library of Virginia Holdings
